# main
PIPELINE_NAME: pointcapsnet

DIRECTORY:
  ROOT_DIRECTORY: /workspace/logs/Spine/SpineCaps
  DATA_DIRECTORY: /workspace/dataset/graph/Spine
  LOGGER_DIRECTORY: log/prior

SEED: 2019
DEVICE: cuda
DEVICE_LIST: [0]
WORKERS: 10

MODEL:
  PY: models.pointcapsnet_prior
  CLASS: PointCapsNet
  ARGS:
    prim_caps_size: 1024
    prim_vec_size: 16
    prior_size: 10
    prior_vec_size: 64
    latent_caps_size: 32
    latent_vec_size: 16
    num_points: 1024

FOLD:
  NUMBER: 5
  USEFOLDS: [0]

FILE: /workspace/dataset/graph/Spine/raw/analysis.csv

# preprocessing

# training
#CRITERION:
#  NAME: CrossEntropyLoss

OPTIMIZER:
  CLASS: RAdam
  ARGS:
    lr: 0.01
    weight_decay: 0.00005

SCHEDULER:
  CLASS: CosineAnnealingWarmRestarts
  ARGS:
    T_0: 2
    T_mult: 2
    eta_min: 0.000001


BATCH_SIZE: 30
ACCUMULATION_STEP: 1
EPOCHS: 3000
EARLY_STOPPING: 200

# saving
CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints
  TOPK: 3

# validation
EVALUATION:
  SEARCH_PAIRS: [[0.3], [0.5], [0.7], [0.9]]